version: "3.9"

services:
  jupyter:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ../:/home/jovyan/
      - ../:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/home/jovyan:$(PYTHONPATH)
