version: "3.9"

services:
  jupyter:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ../:/home/jovyan/
      - ../:/home/jovyan/work
    shm_size: 4g
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/home/jovyan
#    depends_on:
#      - mlflow
#    networks:
#      - mlflow-net

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-server
    ports:
      - "5005:5000"
    volumes:
      - ../mlruns:/mlruns
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlruns/mlflow.db
      --default-artifact-root mlflow-artifacts:/
      --host 0.0.0.0
      --port 5000

#  db:
#    image: postgres:15
#    container_name: postgres
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: public
#    ports:
#      - "5432:5432"
#    volumes:
#      - vmk_thesis:/var/lib/postgresql/data
#
#volumes:
#  vmk_thesis:
#    external: true

networks:
  mlflow-net:
    driver: bridge