y_name: dailycapitalization
y_log: lr__dailycapitalization_1
secid: secid
tradedate: tradedate
year: year
boardid: boardid
inn: inn
is_vacation: is_vacation
issue_cumsum: issue_cumsum
close: close
type: type
sector: sector
x_lr_30: lr__dailycapitalization_30

index_cols:
  - secid
  - tradedate


data_processing:
  filter_boards:
    boards:
      - TQBR
      - EQBR
      - TQBS
      - EQBS
      - TQLV
      - EQLV
      - TQNL
      - EQNL

  drop_additional_issues:
    by:
      - base_secid
      - tradedate
      - boardid
    template: -0.*$

  filter_null_cols:

  categorize:
    cols:
      type: common_share
      sector: other

  gather_secids:

  replace_zeros_with_nan:

  set_index:
    sort_by:
      secid: True
      tradedate: True
      volume: False

  fill_periods:
    freq: D

  ffill_bfill:

  filter_years:
    years:
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019
      - 2020
      - 2021
      - 2022
      - 2023
      - 2024

  filter_secids:
    num: 5000


feature_engineering:
  lowess_smooth:
    col_prefix: sm_
    frac: 0.2

  one_hot_encode:
    cols:
      - sector
      - type

  min_max_scale:
    cols:
      - sm__capital_rsbu
      - sm__current_ratio_msfo
      - sm__debt_ratio_msfo
      - sm__dpr_rsbu
      - sm__dpr_msfo
      - sm__net_working_capital_msfo
      - sm__pffo_rsbu
      - sm__pffo_msfo
      - sm__ps_rsbu
      - sm__line_1140
      - sm__line_2900
      - sm__line_2910
      - sm__line_3212
      - sm__line_3215
      - sm__line_3240
      - sm__line_3315
      - sm__line_3330
      - sm__line_3340
      - sm__line_3400
      - sm__line_3401
      - sm__line_3402
      - sm__line_3410
      - sm__line_3411
      - sm__line_3412
      - sm__line_3420
      - sm__line_3421
      - sm__line_3422
      - sm__line_3500
      - sm__line_3501
      - sm__line_3502
      - sm__line_4113
      - sm__line_421x
      - sm__line_4312
      - sm__line_4314
      - sm__line_431x
      - sm__line_6100
      - sm__line_6200
      - sm__line_6210
      - sm__line_6215
      - sm__line_6220
      - sm__line_6230
      - sm__line_6240
      - sm__line_6250
      - sm__line_6311
      - sm__line_6313
      - sm__line_6320
      - sm__line_6321
      - sm__line_6322
      - sm__line_6323
      - sm__line_6324
      - sm__line_6325
      - sm__line_6326
      - sm__line_6400

  standard_scale:
    cols:
      - sm__capex_revenue_rsbu
      - sm__capex_revenue_msfo
      - sm__capital_msfo
      - sm__current_ratio_rsbu
      - sm__debt_equity_rsbu
      - sm__debt_equity_msfo
      - sm__debt_ratio_rsbu
      - sm__debtebitda_rsbu
      - sm__debtebitda_msfo
      - sm__ebitda_margin_rsbu
      - sm__ebitda_margin_msfo
      - sm__ev_ebit_rsbu
      - sm__ev_ebit_msfo
      - sm__evebitda_rsbu
      - sm__evebitda_msfo
      - sm__evs_rsbu
      - sm__evs_msfo
      - sm__gross_margin_rsbu
      - sm__gross_margin_msfo
      - sm__interest_coverage_rsbu
      - sm__interest_coverage_msfo
      - sm__net_margin_rsbu
      - sm__net_margin_msfo
      - sm__net_working_capital_rsbu
      - sm__netdebt_ebitda_rsbu
      - sm__netdebt_ebitda_msfo
      - sm__operation_margin_rsbu
      - sm__operation_margin_msfo
      - sm__pbv_rsbu
      - sm__pbv_msfo
      - sm__pcf_rsbu
      - sm__pcf_msfo
      - sm__pe_rsbu
      - sm__pe_msfo
      - sm__pfcf_rsbu
      - sm__pfcf_msfo
      - sm__ps_msfo
      - sm__roa_rsbu
      - sm__roa_msfo
      - sm__roce_rsbu
      - sm__roce_msfo
      - sm__roe_rsbu
      - sm__roe_msfo
      - sm__roic_rsbu
      - sm__roic_msfo
      - sm__ros_rsbu
      - sm__ros_msfo
      - sm__line_1100
      - sm__line_1110
      - sm__line_1120
      - sm__line_1130
      - sm__line_1150
      - sm__line_1160
      - sm__line_1170
      - sm__line_1180
      - sm__line_1190
      - sm__line_1200
      - sm__line_1210
      - sm__line_1220
      - sm__line_1230
      - sm__line_1240
      - sm__line_1250
      - sm__line_1260
      - sm__line_1300
      - sm__line_1310
      - sm__line_1320
      - sm__line_1340
      - sm__line_1350
      - sm__line_1360
      - sm__line_1370
      - sm__line_1400
      - sm__line_1410
      - sm__line_1420
      - sm__line_1430
      - sm__line_1450
      - sm__line_1500
      - sm__line_1510
      - sm__line_1520
      - sm__line_1530
      - sm__line_1540
      - sm__line_1550
      - sm__line_1600
      - sm__line_1700
      - sm__line_2100
      - sm__line_2110
      - sm__line_2120
      - sm__line_2200
      - sm__line_2210
      - sm__line_2220
      - sm__line_2300
      - sm__line_2310
      - sm__line_2320
      - sm__line_2330
      - sm__line_2340
      - sm__line_2350
      - sm__line_2400
      - sm__line_2410
      - sm__line_2411
      - sm__line_2412
      - sm__line_2421
      - sm__line_2430
      - sm__line_2450
      - sm__line_2460
      - sm__line_2500
      - sm__line_2510
      - sm__line_2520
      - sm__line_2530
      - sm__line_3100
      - sm__line_3200
      - sm__line_3210
      - sm__line_3211
      - sm__line_3213
      - sm__line_3214
      - sm__line_3216
      - sm__line_321x
      - sm__line_3220
      - sm__line_3221
      - sm__line_3222
      - sm__line_3223
      - sm__line_3224
      - sm__line_3225
      - sm__line_3226
      - sm__line_3227
      - sm__line_322x
      - sm__line_3230
      - sm__line_3300
      - sm__line_3310
      - sm__line_3311
      - sm__line_3312
      - sm__line_3313
      - sm__line_3314
      - sm__line_3316
      - sm__line_331x
      - sm__line_3320
      - sm__line_3321
      - sm__line_3322
      - sm__line_3323
      - sm__line_3324
      - sm__line_3325
      - sm__line_3326
      - sm__line_3327
      - sm__line_332x
      - sm__line_3600
      - sm__line_4100
      - sm__line_4110
      - sm__line_4111
      - sm__line_4112
      - sm__line_4119
      - sm__line_411x
      - sm__line_4120
      - sm__line_4121
      - sm__line_4122
      - sm__line_4123
      - sm__line_4124
      - sm__line_4129
      - sm__line_412x
      - sm__line_4200
      - sm__line_4210
      - sm__line_4211
      - sm__line_4212
      - sm__line_4213
      - sm__line_4214
      - sm__line_4219
      - sm__line_4220
      - sm__line_4221
      - sm__line_4222
      - sm__line_4223
      - sm__line_4224
      - sm__line_4229
      - sm__line_422x
      - sm__line_4300
      - sm__line_4310
      - sm__line_4311
      - sm__line_4313
      - sm__line_4319
      - sm__line_4320
      - sm__line_4321
      - sm__line_4322
      - sm__line_4323
      - sm__line_4329
      - sm__line_432x
      - sm__line_4400
      - sm__line_4450
      - sm__line_4490
      - sm__line_4500
      - sm__line_6300
      - sm__line_6310
      - sm__line_6312
      - sm__line_6330
      - sm__line_6350

  add_log_returns:
    col_prefix: lr_
    features:
      dailycapitalization: [1, 30]


training:
  target_params:
    shift_period: 1
    target_column: bike_count
    new_target_name: target

  train_fraction: 0.8

  model_type: catboost

  model_params:
    catboost:
      learning_rate: 0.2
      depth: 6
      l2_leaf_reg: 1
      iterations: 50 # 500
      loss_function: RMSE
      verbose: 0
      random_seed: 42
      allow_writing_files: false

    random_forest:
      n_estimators: 100
      max_depth: 6
      min_samples_split: 2
      min_samples_leaf: 1
      max_features: 'auto'
      random_seed: 42
      verbose: 0
      allow_writing_files: false

  base_cols:
    - secid
    - tradedate
    - is_vacation
    - issue_cumsum
    - y_name
    - y_log
    - lr__dailycapitalization_30

evaluate:
    metrics:
      - name: RMSE
        function: rmse
      - name: MAE
        function: mae


mults:
  - capex_revenue_rsbu
  - capex_revenue_msfo
  - capital_rsbu
  - capital_msfo
  - current_ratio_rsbu
  - current_ratio_msfo
  - debt_equity_rsbu
  - debt_equity_msfo
  - debt_ratio_rsbu
  - debt_ratio_msfo
  - debtebitda_rsbu
  - debtebitda_msfo
  - dpr_rsbu
  - dpr_msfo
  - ebitda_margin_rsbu
  - ebitda_margin_msfo
  - ev_ebit_rsbu
  - ev_ebit_msfo
  - evebitda_rsbu
  - evebitda_msfo
  - evs_rsbu
  - evs_msfo
  - gross_margin_rsbu
  - gross_margin_msfo
  - interest_coverage_rsbu
  - interest_coverage_msfo
  - net_margin_rsbu
  - net_margin_msfo
  - net_working_capital_rsbu
  - net_working_capital_msfo
  - netdebt_ebitda_rsbu
  - netdebt_ebitda_msfo
  - operation_margin_rsbu
  - operation_margin_msfo
  - pbv_rsbu
  - pbv_msfo
  - pcf_rsbu
  - pcf_msfo
  - pe_rsbu
  - pe_msfo
  - pfcf_rsbu
  - pfcf_msfo
  - pffo_rsbu
  - pffo_msfo
  - ps_rsbu
  - ps_msfo
  - roa_rsbu
  - roa_msfo
  - roce_rsbu
  - roce_msfo
  - roe_rsbu
  - roe_msfo
  - roic_rsbu
  - roic_msfo
  - ros_rsbu
  - ros_msfo

lines:
  - line_1100
  - line_1110
  - line_1120
  - line_1130
  - line_1140
  - line_1150
  - line_1160
  - line_1170
  - line_1180
  - line_1190
  - line_1200
  - line_1210
  - line_1220
  - line_1230
  - line_1240
  - line_1250
  - line_1260
  - line_1300
  - line_1310
  - line_1320
  - line_1340
  - line_1350
  - line_1360
  - line_1370
  - line_1400
  - line_1410
  - line_1420
  - line_1430
  - line_1450
  - line_1500
  - line_1510
  - line_1520
  - line_1530
  - line_1540
  - line_1550
  - line_1600
  - line_1700
  - line_2100
  - line_2110
  - line_2120
  - line_2200
  - line_2210
  - line_2220
  - line_2300
  - line_2310
  - line_2320
  - line_2330
  - line_2340
  - line_2350
  - line_2400
  - line_2410
  - line_2411
  - line_2412
  - line_2421
  - line_2430
  - line_2450
  - line_2460
  - line_2500
  - line_2510
  - line_2520
  - line_2530
  - line_2900
  - line_2910
  - line_3100
  - line_3200
  - line_3210
  - line_3211
  - line_3212
  - line_3213
  - line_3214
  - line_3215
  - line_3216
  - line_321x
  - line_3220
  - line_3221
  - line_3222
  - line_3223
  - line_3224
  - line_3225
  - line_3226
  - line_3227
  - line_322x
  - line_3230
  - line_3240
  - line_3300
  - line_3310
  - line_3311
  - line_3312
  - line_3313
  - line_3314
  - line_3315
  - line_3316
  - line_331x
  - line_3320
  - line_3321
  - line_3322
  - line_3323
  - line_3324
  - line_3325
  - line_3326
  - line_3327
  - line_332x
  - line_3330
  - line_3340
  - line_3400
  - line_3401
  - line_3402
  - line_3410
  - line_3411
  - line_3412
  - line_3420
  - line_3421
  - line_3422
  - line_3500
  - line_3501
  - line_3502
  - line_3600
  - line_4100
  - line_4110
  - line_4111
  - line_4112
  - line_4113
  - line_4119
  - line_411x
  - line_4120
  - line_4121
  - line_4122
  - line_4123
  - line_4124
  - line_4129
  - line_412x
  - line_4200
  - line_4210
  - line_4211
  - line_4212
  - line_4213
  - line_4214
  - line_4219
  - line_421x
  - line_4220
  - line_4221
  - line_4222
  - line_4223
  - line_4224
  - line_4229
  - line_422x
  - line_4300
  - line_4310
  - line_4311
  - line_4312
  - line_4313
  - line_4314
  - line_4319
  - line_431x
  - line_4320
  - line_4321
  - line_4322
  - line_4323
  - line_4329
  - line_432x
  - line_4400
  - line_4450
  - line_4490
  - line_4500
  - line_6100
  - line_6200
  - line_6210
  - line_6215
  - line_6220
  - line_6230
  - line_6240
  - line_6250
  - line_6300
  - line_6310
  - line_6311
  - line_6312
  - line_6313
  - line_6320
  - line_6321
  - line_6322
  - line_6323
  - line_6324
  - line_6325
  - line_6326
  - line_6330
  - line_6350
  - line_6400

macro:
  - key_rate
  - inflation
  - str_li_def_new
  - str_li_def
  - claims
  - action_based_repo_fx
  - action_based_secure_loans
  - standing_facilities_repo_fx
  - standing_facilities_secure_loans
  - liabilities
  - deposit_auction_based
  - deposit_standing_facilities
  - cbr_bonds
  - net_cbr_claims
  - corr_acc
  - avgrr
  - gold_price
  - silver_price
  - platinum_price
  - palladium_price
  - usd_price
  - eur_price
  - ruonia_rate
  - ruonia_volume

dtype_dict_raw:
  secid: str
  tradedate: str
  is_vacation: float
  issue_cumsum: float
  y_name: float
  boardid: str
  primary_boardid: str
  shortname: str
  inn: str
  year: float
  close: float
  volume: int
  sector: category
  type: str
  issuesize: float
  capex_revenue_rsbu: float
  capex_revenue_msfo: float
  capital_rsbu: float
  capital_msfo: float
  current_ratio_rsbu: float
  current_ratio_msfo: float
  debt_equity_rsbu: float
  debt_equity_msfo: float
  debt_ratio_rsbu: float
  debt_ratio_msfo: float
  debtebitda_rsbu: float
  debtebitda_msfo: float
  dpr_rsbu: float
  dpr_msfo: float
  ebitda_margin_rsbu: float
  ebitda_margin_msfo: float
  ev_ebit_rsbu: float
  ev_ebit_msfo: float
  evebitda_rsbu: float
  evebitda_msfo: float
  evs_rsbu: float
  evs_msfo: float
  gross_margin_rsbu: float
  gross_margin_msfo: float
  interest_coverage_rsbu: float
  interest_coverage_msfo: float
  net_margin_rsbu: float
  net_margin_msfo: float
  net_working_capital_rsbu: float
  net_working_capital_msfo: float
  netdebt_ebitda_rsbu: float
  netdebt_ebitda_msfo: float
  operation_margin_rsbu: float
  operation_margin_msfo: float
  pbv_rsbu: float
  pbv_msfo: float
  pcf_rsbu: float
  pcf_msfo: float
  pe_rsbu: float
  pe_msfo: float
  pfcf_rsbu: float
  pfcf_msfo: float
  pffo_rsbu: float
  pffo_msfo: float
  ps_rsbu: float
  ps_msfo: float
  roa_rsbu: float
  roa_msfo: float
  roce_rsbu: float
  roce_msfo: float
  roe_rsbu: float
  roe_msfo: float
  roic_rsbu: float
  roic_msfo: float
  ros_rsbu: float
  ros_msfo: float
  line_1100: float
  line_1110: float
  line_1120: float
  line_1130: float
  line_1140: float
  line_1150: float
  line_1160: float
  line_1170: float
  line_1180: float
  line_1190: float
  line_1200: float
  line_1210: float
  line_1220: float
  line_1230: float
  line_1240: float
  line_1250: float
  line_1260: float
  line_1300: float
  line_1310: float
  line_1320: float
  line_1340: float
  line_1350: float
  line_1360: float
  line_1370: float
  line_1400: float
  line_1410: float
  line_1420: float
  line_1430: float
  line_1450: float
  line_1500: float
  line_1510: float
  line_1520: float
  line_1530: float
  line_1540: float
  line_1550: float
  line_1600: float
  line_1700: float
  line_2100: float
  line_2110: float
  line_2120: float
  line_2200: float
  line_2210: float
  line_2220: float
  line_2300: float
  line_2310: float
  line_2320: float
  line_2330: float
  line_2340: float
  line_2350: float
  line_2400: float
  line_2410: float
  line_2411: float
  line_2412: float
  line_2421: float
  line_2430: float
  line_2450: float
  line_2460: float
  line_2500: float
  line_2510: float
  line_2520: float
  line_2530: float
  line_2900: float
  line_2910: float
  line_3100: float
  line_3200: float
  line_3210: float
  line_3211: float
  line_3212: float
  line_3213: float
  line_3214: float
  line_3215: float
  line_3216: float
  line_321x: float
  line_3220: float
  line_3221: float
  line_3222: float
  line_3223: float
  line_3224: float
  line_3225: float
  line_3226: float
  line_3227: float
  line_322x: float
  line_3230: float
  line_3240: float
  line_3300: float
  line_3310: float
  line_3311: float
  line_3312: float
  line_3313: float
  line_3314: float
  line_3315: float
  line_3316: float
  line_331x: float
  line_3320: float
  line_3321: float
  line_3322: float
  line_3323: float
  line_3324: float
  line_3325: float
  line_3326: float
  line_3327: float
  line_332x: float
  line_3330: float
  line_3340: float
  line_3400: float
  line_3401: float
  line_3402: float
  line_3410: float
  line_3411: float
  line_3412: float
  line_3420: float
  line_3421: float
  line_3422: float
  line_3500: float
  line_3501: float
  line_3502: float
  line_3600: float
  line_4100: float
  line_4110: float
  line_4111: float
  line_4112: float
  line_4113: float
  line_4119: float
  line_411x: float
  line_4120: float
  line_4121: float
  line_4122: float
  line_4123: float
  line_4124: float
  line_4129: float
  line_412x: float
  line_4200: float
  line_4210: float
  line_4211: float
  line_4212: float
  line_4213: float
  line_4214: float
  line_4219: float
  line_421x: float
  line_4220: float
  line_4221: float
  line_4222: float
  line_4223: float
  line_4224: float
  line_4229: float
  line_422x: float
  line_4300: float
  line_4310: float
  line_4311: float
  line_4312: float
  line_4313: float
  line_4314: float
  line_4319: float
  line_431x: float
  line_4320: float
  line_4321: float
  line_4322: float
  line_4323: float
  line_4329: float
  line_432x: float
  line_4400: float
  line_4450: float
  line_4490: float
  line_4500: float
  line_6100: float
  line_6200: float
  line_6210: float
  line_6215: float
  line_6220: float
  line_6230: float
  line_6240: float
  line_6250: float
  line_6300: float
  line_6310: float
  line_6311: float
  line_6312: float
  line_6313: float
  line_6320: float
  line_6321: float
  line_6322: float
  line_6323: float
  line_6324: float
  line_6325: float
  line_6326: float
  line_6330: float
  line_6350: float
  line_6400: float
  key_rate: float
  inflation: float
  str_li_def_new: float
  str_li_def: float
  claims: float
  action_based_repo_fx: float
  action_based_secure_loans: float
  standing_facilities_repo_fx: float
  standing_facilities_secure_loans: float
  liabilities: float
  deposit_auction_based: float
  deposit_standing_facilities: float
  cbr_bonds: float
  net_cbr_claims: float
  corr_acc: float
  avgrr: float
  gold_price: float
  silver_price: float
  platinum_price: float
  palladium_price: float
  usd_price: float
  eur_price: float
  ruonia_rate: float
  ruonia_volume: float


#dtype_dict:
#  ${secid}: str
#  ${tradedate}: str
#  ${is_vacation}: float
#  ${issue_cumsum}: float
#  ${y_name}: float
#  cat__sector_consumer: float
#  cat__sector_energy: float
#  cat__sector_financial: float
#  cat__sector_health_care: float
#  cat__sector_industrials: float
#  cat__sector_it: float
#  cat__sector_materials: float
#  cat__sector_other: float
#  cat__sector_real_estate: float
#  cat__sector_telecom: float
#  cat__sector_utilities: float
#  cat__type_common_share: float
#  cat__type_preferred_share: float
